### ISSUE TITLE
After upgrading to 0.6.0 I get a JSCS processing error

### ISSUE THREAD

**Issue by ptakes** [globexdesigns/brackets-jscs#23]
Unexpected JSCS processing error: Unable to load one of the modules: C:/Users/Peter/AppData/Roaming/Brackets/extensions/user/globexdesigns.brackets-jscs/domain, reason: Cannot find module 'jscs'

**Comment by attilacsanyi** [comment]
I have the same problem, thanks for the quick fix

**Comment by globexdesigns** [comment]
I've just pushed version 0.6.1, can you please try that?

@ptakes  You'll also need to make sure you run this `npm install -g jscs` and then restart Brackets.

**Comment by attilacsanyi** [comment]
Dear @globexdesigns unfortunately the problem is the same, jscs module not found. It seems only win issue?

**Comment by ptakes** [comment]
I tested 0.6.1 both upgrade and complete reinstall, but problem remains. I am also running on Windows like attilacsanyi, could be indeed a Windows only issue.

**Comment by globexdesigns** [comment]
Actually, I've tested 0.6.x only on WIndows so it should work. I'll keep looking into it.

**Comment by attilacsanyi** [comment]
I am using windows 8 64 bit, perhaps this is also matters

**Comment by globexdesigns** [comment]
Can you please try this 0.6.2 build: https://www.dropbox.com/s/ie8a8y9wk6b1nj6/brackets-jscs-0.6.2.zip?dl=0 You'll have to unzip it into your Brackets Extensions folder (and delete the old globexdesigns.brackets-jscs extension in there). The restart Brackets.

It will not fix the issue, but it will now print a new error message. Something like this: 

```
Unable to load one of the modules: C:/Users/Guy/AppData/Roaming/Brackets/extensions/user/globexdesigns.brackets-jscs/domain, reason: Unable to start brackets-jscs due to error: "Cannot find module 'jscs'". NODE_PATH is: C:\Users\Guy\AppData\Roaming\npm\node_modules;C:\Users\Guy\AppData\Roaming\npm\node_modules
```

Make a note of the NODE_PATH value specified at the end of the message. Go to that directory (in my case it's C:\Users\Guy\AppData\Roaming\npm\node_modules) and make sure that `jscs` is installed in there. If it's not - something is out-of-the-ordinary going on with the configured global NODE_PATH on your machine.

When you run `npm install -g jscs` it should be installing the module into the directory. If it isn't, let me know the following:
1) What the error prints as your NODE_PATH, and
2) Where the `jscs` module ends up being installed after you type `npm install -g jscs`

**Comment by ptakes** [comment]
Here you go:

Unexpected JSCS processing error: Unable to load one of the modules: C:/Users/Peter/AppData/Roaming/Brackets/extensions/user/globexdesigns.brackets-jscs/domain, reason: Unable to start brackets-jscs due to error: "Cannot find module 'jscs'". NODE_PATH is: C:\Users\Peter\AppData\Roaming\npm\node_modules

I checked the NODE_PATH, and the jscs module is there (C:\Users\Peter\AppData\Roaming\npm\node_modules\jscs), could it be a permission thing? I am running Windows 8.1 64-bit.

**Comment by attilacsanyi** [comment]
I have the same OS and got the same error message above like @ptakes really weird. If I run bracket with administrator privileges I got the same. Hmmm.

**Comment by globexdesigns** [comment]
Ok, I've pushed a final 0.6.2 release to the registry which has JSCS embedded with the extension itself. I was hoping to avoid this so that users could update their local copies of JSCS instead of me having to bundle the latest JSCS version with each extension release... but, oh well.

I'll try to work with the Brackets team to find out why this isn't working as it should for all users, but until then, the latest release should just work right out of the box without having to install anything extra.

**Comment by attilacsanyi** [comment]
Dear @globexdesigns thanks for your quick resolution. I also hope there will be a better approach so I will check this extension regularly. Thanks again!

**Comment by globexdesigns** [comment]
@attilacsanyi Could you do me another favour? Can you please:

- Download the new 0.6.3 extension from https://www.dropbox.com/s/ih7tyqft8w01sui/brackets-jscs-0.6.3.zip?dl=0
- Uninstall the current brackets-jscs extension from Brackets
- Install the 0.6.3 version of the extension by unzipping the downloaded package into your Extensions folder
- Make sure you've got `npm install -g jscs` installed
- Restart Brackets
- See if the extension works with the global JSCS now

I tried it on a few Windows machines, including ones where 0.6.0 wasn't working and I think I've got this figured out.

**Comment by ptakes** [comment]
Yep, it is working now. Thank you for solving this so quickly.

**Comment by globexdesigns** [comment]
@ptakes Can you try the 0.6.3 build using the instructions in my comment above as well?

**Comment by ptakes** [comment]
I did test 0.6.3 following your instructions and everything is working now.

**Comment by attilacsanyi** [comment]
Dear @globexdesigns it was working for me as well. Great job!

**Comment by globexdesigns** [comment]
Thanks guys! I'll push 0.6.3 out.

**Comment by RonniePoulsen** [comment]
Hi @globexdesigns. I am new with the Brackets editor and I am trying to get brackets-jscs to work. Right now I am facing the exact same problem as @ptakes did in the beginning of this issue thread. How ever I have tried all solutions written in this thread with no luck. Can you please help me fix this?

I have posted a question over at Stackoverflow so I am hoping some one can point me in the right direction as I am pretty stuck right now.

http://stackoverflow.com/questions/32882744/adobe-brackets-jscs-extension-cannot-find-module-findup

Thanks in advance.

**Comment by globexdesigns** [comment]
@RonniePoulsen Based on your StackOverflow info, it seems like you're running the extension by installing it directly from the Github repo. Is that right? Can you try removing the extension and then installing it via the Brackets Registry instead?

**Comment by RonniePoulsen** [comment]
Hi @globexdesigns. Yes you're right. But I tried with both versions with no luck. I have now tried to get it working on my other computer with no problems at all. So then I uninstalled all packages and then reinstalled. Now it's working and I have no idea why haha. I guess there must have been a problem with some path references or something.

**Comment by globexdesigns** [comment]
Yeah, the installation is a bit messy right now just because everyone's npm setup is slightly differently. So to make it work for everyone, there's a bit of a hoop you have to jump through to get it setup. Glad you got it working.

**Comment by Dedice** [comment]
Unexpected JSCS processing error: Unable to load one of the modules: C:/Users/Andrei/AppData/Roaming/Brackets/extensions/user/globexdesigns.brackets-jscs/domain, reason: Cannot find module 'colors'

**Comment by ivan-yosifov** [comment]
Link to Dropbox is not working

**Comment by globexdesigns** [comment]
@ivan-yosifov It is no longer needed. The official release no longer suffers from this issue.
